[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sdr-setup"
authors = [{name = "EliteArcanist", email = "andrew@jmcdfam.net"}]
dynamic = ["version", "description"]

[tool.esbonio.sphinx]
pythonCommand = ["${env:./venv}"]
